### ISSUE TITLE
Include more APIs in documentation

### ISSUE THREAD

**Issue by dfkeenan** [xenko3d/xenko-docs#4]
Currently quite a few assemblies are not included in the API documentation. Even one of the basics like `Xenko.Core.Mathematics` which is kind of important. Should probably include some if not all public APIs.

**Comment by xen2** [comment]
Thanks for pointing it out.

Seems there was some issues during the namespace mass rename:
In  https://github.com/xenko3d/xenko-docs/blob/master/en/docfx.json I can see:
```
              "sources/core/Xenko.Core.Core.Mathematics/Xenko.Core.Core.Mathematics.csproj",
              "sources/core/Xenko.Core.Core.MicroThreading/Xenko.Core.Core.MicroThreading.csproj",
              "sources/core/Xenko.Core.Core.Serialization/Xenko.Core.Core.Serialization.csproj",
```
(notice the `Core.Core`)

Will fix that.

**Comment by dfkeenan** [comment]
It's been a problem for a while. https://github.com/SiliconStudio/xenko/issues/655

:D

**Comment by Kryptos-FR** [comment]
@xen2 try to include editor API as well.

I think that later runtime and editor should probably be in two different sections on the website but we can improve later.

**Comment by xen2** [comment]
@Kryptos-FR Sure, I will do it little bit later (Core is trivial but Editor is not -- I need to test locally before pushing live)

**Comment by xen2** [comment]
It's live.
Might still need to rearrange TOC so that `Xenko.Core.*` subnamespaces are directly in the top level TOC rather than being nested in `Xenko.Core`
